# Generated by Django 4.1.3 on 2022-11-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='newaction', max_length=180, verbose_name='Hareket İsmi')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('activity', models.IntegerField(default=0, verbose_name='Aktiflik')),
            ],
        ),
    ]
