# Generated by Django 4.1.3 on 2022-11-22 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseVideo',
            new_name='Hareket',
        ),
    ]
